name       : python-requests-toolbelt
version    : 0.8.0
release    : 1
source     :
    - https://github.com/requests/toolbelt/archive/0.8.0.tar.gz : f151c07e88148dc05b6f31cc75dfb7a6770968e4a5c8e6690325eed4e79160a1
license    : Apache-2.0
component  : programming.python
summary    : A toolbelt of useful classes and functions to be used with python-requests
description: |
    This is just a collection of utilities for python-requests, but don't really belong in requests proper.
builddeps  :
    - python-betamax
    - python-mock
    - python-pytest
rundeps    :
    - python-requests
build      : |
    %python_setup
install    : |
    %python_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        py.test -v
    popd
