name       : python-requests-toolbelt
version    : 0.9.1
release    : 6
source     :
    - https://github.com/requests/toolbelt/archive/0.9.1.tar.gz : c8e68e537e87ae088e3a0eb6d80ed5b7cf5d6df503d0e843e0a5e47283db487b
license    : Apache-2.0
component  : programming.python
summary    : A toolbelt of useful classes and functions to be used with python-requests
description: |
    This is just a collection of utilities for python-requests, but don't really belong in requests proper.
builddeps  :
    - python-betamax
    - python-mock
    - python-pytest
rundeps    :
    - python-requests
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test
